apps/dashboard/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [

    url(r'^$', views.dash, name='dash'),
    url(r'^ready/$', views.assignments, name='assignments'),
    url(r'^clear/$', views.clear, name='clear'),
    url(r'^add/(?P<id>\d+)/$', views.addtoplans, name='addtoplans'),
    url(r'^return/(?P<id>\d+)/$', views.remfromplans, name='remfromplans'),
    url(r'^set/$', views.commit, name='commit'),
    url(r'^go/$', views.go, name='go'),
    url(r'^dozo/$', views.dozo, name='dozo'),
    url(r'^archive/$', views.archive, name='archive'),

]

apps/landing/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [

    url(r'^$', views.home, name='home'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),

]

dozo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.landing import views

urlpatterns = [
    
    # Django
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('django.contrib.auth.urls')), # for login within Dozo

    # Apps
    url(r'^', include('apps.landing.urls', namespace='landing')),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace='dashboard')),

    # later, have a user profile page
    # return redirect(reverse('users:show', kwargs={'id': your_id_variable }))

]

apps/landing/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# Import models and validations from Django
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.core.exceptions import ValidationError

# 
from django.core.cache import cache 
import datetime
from dozo import settings


# Create custom validators
# See forms.py for password confirmation validator
def lenLessThanThree(value):
    if len(value) < 3:
        raise ValidationError('Error: Word length')

def lenLessThanEight(value):
    if len(value) < 8:
        raise ValidationError('Error: Word length')


# Manager for user creation
class UserManager(BaseUserManager):

    def create_user(self, username, first_name, email, password = None):
        user = self.model(
            username = username,
            first_name = first_name,
            email = self.normalize_email(email)
        )
        user.set_password(password)
        user.save(using = self._db)
        return user

    def create_superuser(self, username, first_name, email, password = None):
        user = self.create_user(
            username,
            first_name,
            email,
            password=password
        )
        user.is_admin = True
        user.save(using = self._db)
        return user


# Create user Model (replaces Django's auth.Model)
class User(AbstractBaseUser):
    
    first_name = models.CharField(max_length=45, validators=[lenLessThanThree])
    last_name = models.CharField(max_length=45)
    username = models.CharField(max_length=45, unique=True, validators=[lenLessThanThree])
    email = models.EmailField(max_length=45, unique=True)
    password = models.CharField(max_length=100, validators=[lenLessThanEight])
    added = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_online = models.BooleanField(default=False)

    # Instantiate userManager object
    objects = UserManager()

    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'email']

    def get_full_name(self):
        return self.first_name, self.last_name

    def get_short_name(self):
        return self.first_name

    def __str__(self):
        return self.username

    def has_perm(self, perm, objec=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

apps/landing/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from .models import User
from ..newsfeed.models import Scorecard


# Join Dozo
class CreateUser(forms.ModelForm):

    # Create password and confirmation fields to check
    password1 = forms.CharField(
        label='Password', widget=forms.PasswordInput, help_text="8 characters minimum")
    password2 = forms.CharField(
        label='Confirm Password', widget=forms.PasswordInput, help_text="Must be an exact match")

    # Custom field labels / help text
    first_name = forms.CharField(help_text="3 characters minimum")
    username = forms.CharField(help_text="3 characters minimum")
    last_name = forms.CharField(required=False, help_text="Optional")
    email = forms.EmailField(help_text="Must be valid format")

    # Set meta of form inputs to be User model
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

    # Check that the two password entries match
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Error: Passwords did not match.")
        return password2

    # Create user with hashed password
    def save(self, commit=True):
        user = super(CreateUser, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
            # Add scorecard to new user
            Scorecard.objects.create(user=user)
        return user

apps/landing/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


# All the usuals
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST


# Models and forms
from models import User
from forms import CreateUser


# Home
def home(request):

    # Render registration form created in forms.py
    form = { "form": CreateUser() }

    return render(request, 'landing/index.html', form)
    

@require_POST
def register(request):

    # Pass post data into the ModelForm to validate before saving
    form = CreateUser(request.POST)

    # If valid, save and use post data to auto-login
    if form.is_valid():
        form.save()
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=raw_password)
        login(request, user)
        return redirect(reverse('dashboard:dash'))
        
    # Re-render the form with invalid data passed in
    else: # Django will take care of rendering validations!
        form = { "form": CreateUser(request.POST) }
        return render(request, 'landing/index.html', form)


def logout_user(request):

    # Set offline status
    if request.user.is_online == True:
        request.user.is_online = False
        request.user.save()

    return redirect('/auth/logout')

apps/landing/templates/landing/base.html
<!DOCTYPE html>
<html lang=en>
<head>
    {% block title %}<title>Dozo</title>{% endblock %}
    <meta charset=utf-8>
    <meta name=viewport content=width=device-width, initial-scale=1>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    {% load static %}
    <link rel=stylesheet href={% static 'landing/style.css' %}>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<div class=container>

<nav class="navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href='{% url 'landing:home' %}' class="navbar-brand">Dozo</a>
    </div>
    <ul class="nav navbar-nav">
        {% if user.is_authenticated %}
        {% if current|length or done|length %}
        <li><a href="{% url 'dashboard:dozo' %}">Dashboard</a></li>
        {% else %}
        <li><a href="{% url 'dashboard:dash' %}">Dashboard</a></li>
        {% endif %}
        <li><a href=#>Leaderboard</a></li>
        {% endif %}
    </ul>


    <ul class="nav navbar-nav navbar-right">
    {% if not user.is_authenticated %}
    <li>
        {% if form.errors %}
            <p class="label label-danger">Error: Unable to authenticate</p>
        {% endif %}
    </li>
    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-log-in"></span> Login</a></a>
	<ul id="login-dp" class="dropdown-menu">
	<li><div class="row"><div class="col-md-12">
		<form id=login-form class=form method=post action="{% url 'login' %}">{% csrf_token %}
		<div class="input-group"><span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
        <input type=text class=form-control id=id_username placeholder=Username name=username required></div>
		<div class="input-group"><span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
		<input type=password class=form-control id=id_password placeholder=Password name="password" required>
		</div><div><br>
		<button type="submit" class="btn btn-primary btn-block">Login</button>
        </div>
        <input type="hidden" name="next" value="{{ next }}" /><br>
	    </form>
	</div></div></li></ul></li>
    {% else %}
    <li><a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> {{request.user.username}}</a>
	<ul id="login-dp" class="dropdown-menu tab">
	<li><div class="row tab"><div class="col-md-12 tab">
        <small>
            <p>Logged in at {{request.user.last_login}} ({{request.user.last_login|timesince}} online)</p>
            <p>{{user_assignments}} assignments in {{user_sessions}} sessions since {{request.user.added|date:"n/j/y"}}</p>
            <p>More stats go here later</p>
        </small><br>
	</div></div></li></ul></li>
    <li><a href="{% url 'landing:logout_user' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
    {% endif %}
    </ul>
  </div>
</nav>

<div class=row>
<div class=col-md-12>
{% block content %}{% endblock %}
</div>
</div>

<div class=row>
    {% if user.is_authenticated %}
    <div class="col-md-12">
    <small><span class="badge">{{online_users|length}}</span> users currently online</small>
    </div>
    {% endif %}
</div>

<div class=row>&nbsp;</div>


</body>

</html>

apps/landing/templates/landing/index.html
{% extends "landing/base.html" %}
{% block content %}

  <div class="jumbotron container-fluid col-md-8">
    <h1><strong><em>Dozo</em></strong></h1> 
    <h2>Dozo is a data-driven
      <br>productivity & goal-targeting tool
      <br>created to help students improve their
      <br>work efficiency by habituating a
      <br>continuous flow of uninterrupted work.
    </h2>
    <h3>
      With Dozo, you can:
    <ul>
      <li>Plan a work session with time estimates for each task</li>
      <li>Analyze task completion with instantaneous feedback</li>
      <li>Measure your growth alongside of other platform users via a quantifiable points system</li>
      <li>Visualize your progress with data-rich dashboards that show your session and task history*</li>
    </ul>
    </h3>
    <p><small>* Still a work in progress</small></p>
  </div>

  <p>&nbsp;</p>
  <p>&nbsp;</p>
  
  <div class=col-md-4>

    {% if not user.is_authenticated %}

    {% load i18n widget_tweaks %}
    <form method=post action=/register/ class="form" id="register">
    {% csrf_token %}
    <h2>Join <em>Dozo</em></h2>
    {% for field in form %}
        <p>
        <small>{{ field.label_tag }}</small> <small class=text-muted>({{ field.help_text }})</small>
        {{ field|attr:"class:form-control input-sm"}}
        {% for error in field.errors %}
        <small style="color: red">{{ error }}</small>
        {% endfor %}
        </p>
    {% endfor %}
    <br>
    <button type="submit" class="btn btn-primary">Join</button>
    <button type="reset" class="btn btn-secondary">Clear</button>

    {% else %}

    <p>&nbsp;</p>
    <hr>
    <h4>
      Featuring the following tracks from
      <br>the Coding Dojo learning platform:
      <br><br>
      Python:
      <ul>
        <li>Fundamentals</li>
        <li>Object-Oriented Programming</li>
        <li>Flask</li>
        <li>MySQL</li>
        <li>Flask + MySQL</li>
        <li>Django</li>
        <li>Django ORM</li>
      </ul>
      <br>
      Java:
      <ul>
        <li>Fundamentals</li>
        <li>Object-Oriented Programming</li>
        <li>Spring</li>
        <li>Spring Data</li>
        <li>Much more...</li>
      </ul>
    </h4>
    <hr>
    {% endif %}

  </div>

  
{% endblock %}