apps/dashboard/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [

    url(r'^$', views.dash, name='dash'),
    url(r'^ready/$', views.assignments, name='assignments'),
    url(r'^clear/$', views.clear, name='clear'),
    url(r'^add/(?P<id>\d+)/$', views.addtoplans, name='addtoplans'),
    url(r'^return/(?P<id>\d+)/$', views.remfromplans, name='remfromplans'),
    url(r'^set/$', views.commit, name='commit'),
    url(r'^go/$', views.go, name='go'),
    url(r'^dozo/$', views.dozo, name='dozo'),
    url(r'^archive/$', views.archive, name='archive'),

]

dozo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.landing import views

urlpatterns = [
    
    # Django
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('django.contrib.auth.urls')), # for login within Dozo

    # Apps
    url(r'^', include('apps.landing.urls', namespace='landing')),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace='dashboard')),

    # later, have a user profile page
    # return redirect(reverse('users:show', kwargs={'id': your_id_variable }))

]

apps/dashboard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from ..landing.models import User

from datetime import timedelta


class Session(models.Model):
    user = models.ForeignKey(User, related_name="sessions", on_delete=models.CASCADE)
    potential = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    actual = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    start = models.DateTimeField(default=None, blank=True, null=True)
    end = models.DateTimeField(default=None, blank=True, null=True)
    est_duration = models.DurationField(default=timedelta())
    time_bonus = models.DurationField(default=timedelta())
    time_challenge = models.DurationField(default=timedelta())
    act_duration = models.DurationField(default=timedelta())
    on_time = models.BooleanField(default=False)


class Assignment(models.Model):

    TRACKS = (
        ('pyfun1', 'Python Fundamentals 1'),
        ('pyfun2', 'Python Fundamentals 2'),
        ('pyoop', 'Python OOP'),
        ('flask1', 'Flask Fundamentals'),
        ('mysql', 'MySQL'),
        ('flask2', 'Flask with MySQL'),
        ('django', 'Django'),
        ('djangoorm', 'Django ORM'),
        ('javafun', 'Java Fundamentals'),
        ('javaoop', 'Java OOP'),
        ('javaspring1', 'Java Spring 1'),
        ('javaspringdata', 'Java Spring Data'),
        ('javaspring2', 'Java Spring 2'),
    )

    LANE = (
        ('a', 'assignments'),
        ('b', 'plans'),
        ('c', 'commit'),
        ('d', 'current'),
        ('e', 'done'),
        ('f', 'display')
    )

    user = models.ForeignKey(User, related_name="assignments", on_delete=models.CASCADE)
    session = models.ForeignKey(Session, related_name="assignments", blank=True, null=True)
    track = models.CharField(max_length=45, choices=TRACKS)
    status = models.CharField(max_length=45, choices=LANE, default='a')
    title = models.CharField(max_length=45)
    pageid = models.CharField(max_length=45)
    optional = models.BooleanField(default=False)

    # measurements for calculations
    base_points = models.IntegerField()
    time_mult = models.DecimalField(max_digits=3, decimal_places=1)
    est_duration = models.DurationField(default=timedelta())

    # to update via events
    potential = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    start_time = models.DateTimeField(blank=True, null=True)
    end_time = models.DateTimeField(blank=True, null=True)
    act_duration = models.DurationField(default=timedelta())
    on_time = models.BooleanField(default=False) # calculate from duration
    actual = models.DecimalField(max_digits=10, decimal_places=2, default=0, blank=True, null=True)

apps/dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# All the usuals
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

# Models and forms
from ..landing.models import User
from ..newsfeed.models import Scorecard, Event
from models import Assignment, Session
from calculations import *
from assignments import *

# Import time ops
import datetime
from django.utils import timezone


# Home
@login_required(login_url='/')
def dash(request):

    # Set online status upon login
    if request.user.is_online == False:
        request.user.is_online = True
        request.user.save()
    
    # if not archived assignments, redirect to dash2
    if request.user.assignments.filter(status='e').count() > 0:
        return redirect(reverse('dashboard:dozo'))

    # if still in session, redirect to dash2
    if request.user.assignments.filter(status='d').count() > 0:
        return redirect(reverse('dashboard:dozo'))
    
    context = {
        'online_users': User.objects.filter(is_online=True),
        'user_assignments': len(request.user.assignments.filter(status='e')|request.user.assignments.filter(status='f')),
        'user_sessions': request.user.sessions.all().count(),
        'assignments': request.user.assignments.filter(status='a'),
        'plans': request.user.assignments.filter(status='b'),
        'commit': request.user.assignments.filter(status='c'),
        'current': request.user.assignments.filter(status='d'),
        'done': request.user.assignments.filter(status='e').order_by("-id")
    }

    # run function to calculate total potential points
    if request.user.assignments.filter(status='b').count() > 0:
        potential = potential_points(request.user)
        context['potential'] = potential
    elif request.user.assignments.filter(status='c').count() > 0:
        potential = potential_points(request.user)
        context['potential'] = potential
    else:
        context['potential'] = 0

    # run function to calculate total est_duration and time challenge
    if request.user.assignments.filter(status='b').count() > 0:
        duration, bonus, challenge = time_challenge(request.user)
        context['duration'] = duration
        context['bonus'] = bonus
        context['challenge'] = challenge
    elif request.user.assignments.filter(status='c').count() > 0:
        duration, bonus, challenge = time_challenge(request.user)
        context['duration'] = duration
        context['bonus'] = bonus
        context['challenge'] = challenge
    else:
        context['duration'] = timedelta()
        context['bonus'] = timedelta()
        context['challenge'] = timedelta()

    return render(request, 'dashboard/dash.html', context)



# Add Assignments
@require_POST
def assignments(request):

    if request.POST['track'] == 'pyfun1':
        pyfun1(request.user)

    if request.POST['track'] == 'pyfun2':
        pyfun2(request.user)

    if request.POST['track'] == 'pyoop':
        pyoop(request.user)

    if request.POST['track'] == 'flask1':
        flask1(request.user)

    if request.POST['track'] == 'mysql':
        mysql(request.user)

    if request.POST['track'] == 'flask2':
        flask2(request.user)

    if request.POST['track'] == 'django':
        django(request.user)

    if request.POST['track'] == 'djangoorm':
        djangoorm(request.user)

    if request.POST['track'] == 'javafun':
        javafun(request.user)

    if request.POST['track'] == 'javaoop':
        javaoop(request.user)

    if request.POST['track'] == 'javaspring1':
        javaspring1(request.user)

    if request.POST['track'] == 'javaspringdata':
        javaspringdata(request.user)

    if request.POST['track'] == 'javaspring2':
        javaspring2(request.user)

    return redirect(reverse('dashboard:dash'))


# Assignments -> Plans
def addtoplans(request, id):
    
    # if user committed already, don't add assignment to session
    if request.user.assignments.filter(status='c').count() > 0:
        return redirect(reverse('dashboard:dash'))
    
    # if not commited, add assignments to plans
    plan = Assignment.objects.get(id=id)
    plan.status = 'b'
    plan.save()

    return redirect(reverse('dashboard:dash'))


# Clear assignments list
def clear(request):
    if request.user.assignments.filter(status='a').count() == 0:
        return redirect(reverse('dashboard:dash'))
    else:
        for assignment in request.user.assignments.filter(status='a'):
            assignment.delete()
        return redirect(reverse('dashboard:dash'))


# Assignments <- Plans
def remfromplans(request, id):
    
    # move assignment back to lane
    plan = Assignment.objects.get(id=id)
    plan.status = 'a'
    plan.save()

    return redirect(reverse('dashboard:dash'))



# Commit Plans
def commit(request):
    
    # if no plans to commit, redirect to dashboard!
    if request.user.assignments.filter(status='b').count() == 0:
        return redirect(reverse('dashboard:dash'))
    
    # commit plans by updating status field
    for assignment in request.user.assignments.filter(status='b'):
        assignment.status = 'c'
        assignment.save()

    # get est_duration and challenge
    duration, bonus, challenge = time_challenge(request.user)
    
    # create scoreboard and add assignments and calcs to it
    Session.objects.create(
        user = request.user, 
        potential = potential_points(request.user), 
        est_duration = duration,
        time_bonus = bonus,
        time_challenge = challenge)
    session = request.user.sessions.last()
    for assignment in request.user.assignments.filter(status='c'):
        session.assignments.add(assignment)
        assignment.save()

    return redirect(reverse('dashboard:dash'))


# Start continuous work queue
def go(request):
    
    # If session start time not recorded, record
    session = request.user.sessions.last()
    if session.start == None:
        session.start = timezone.now()
        session.save()
    
    # query assignments in lanes
    # note: query stored in a variable stores as uniterable object
    commit = request.user.assignments.filter(status='c')
    current = request.user.assignments.filter(status='d')
    done = request.user.assignments.filter(status='e')

    # if all assignments done (after results), redirect to dashboard
    if request.user.assignments.filter(
        status='c').count() == 0 and request.user.assignments.filter(
        status='d').count() == 0:

        return redirect(reverse('dashboard:dash'))

    # if assignment just finished, update to done and log times
    if request.user.assignments.filter(status='d').count() == 1:
        done = request.user.assignments.get(status='d')
        done.status = 'e'
        done.end_time = timezone.now()
        done.act_duration = done.end_time - done.start_time
        if done.act_duration < done.est_duration:
            done.on_time = True # update on_time bool
        if done.act_duration < timedelta(minutes=5):
            done.act_duration = timedelta(minutes=5)
        done.save()

        # record session end time
        # get session duration from assignments
        # (to account for 1 minute rule)
        session.end = timezone.now()
        session.act_duration = session.end - session.start
        dones = request.user.assignments.filter(status='d')
        if session.act_duration < timedelta(minutes=dones.count() * 5):
            session.act_duration = timedelta(minutes=dones.count() * 5)
        if session.act_duration < session.time_challenge:
            session.on_time = True
        session.save()

        # add points to the scorecard for the session
        # calculate final score if session is done
        actual_points(request.user)

    # if assignments in queue, start new assignment
    if request.user.assignments.filter(status='c').count() > 0:
        start_new = request.user.assignments.filter(status='c').first()
        start_new.status='d'
        start_new.start_time = timezone.now()
        start_new.save()

    return redirect(reverse('dashboard:dozo'))


# DOZO
@login_required(login_url='/')
def dozo(request):
    
    context = {
        'all_current': Assignment.objects.filter(status='d'),
        'user_assignments': len(request.user.assignments.filter(status='e')|request.user.assignments.filter(status='f')),
        'user_sessions': request.user.sessions.all().count(),
        'online_users': User.objects.filter(is_online=True),
        'assignments': request.user.assignments.filter(status='a'),
        'commit': request.user.assignments.filter(status='c'),
        'current': request.user.assignments.filter(status='d'),
        'done': request.user.assignments.filter(status='e').order_by("-id"),
        'stats': request.user.assignments.filter(status='e'),
        'session': request.user.sessions.last(),
        'remaining': len(request.user.assignments.filter(status='c')|request.user.assignments.filter(status='d'))
    }

    return render(request, 'dashboard/dash2.html', context)


# Done -> Display
def archive(request):
    
    # move assignments to 'display' status
    for assignment in Assignment.objects.filter(status='e'):
        assignment.status = 'f'
        assignment.save()

    # update scorecard
    calc_scorecard(request.user)

    return redirect(reverse('dashboard:dash'))

apps/dashboard/templates/dashboard/dash.html
{% extends "landing/base.html" %}

{% block content %}

<div class=kanban>

<div class="lane">
<h4 class=center><span class="glyphicon glyphicon-th-list"></span> Your Assignments</h4><hr>

{% if not assignments|length %}

    <p><strong>Step 1: Select a Track</strong></p>
    
    <p>Select a track from the menu:</p>
    

    <form method=POST action="{% url 'dashboard:assignments' %}">
        <div class=form_group>{% csrf_token %}
            <select name=track class=form-control placeholder=Python>
                <option value=pyfun1>Python Fundamentals 1</option>
                <option value=pyfun2>Python Fundamentals 2</option>
                <option value=pyoop>Python OOP</option>
                <option value=flask1>Flask Fundamentals</option>
                <option value=mysql>MySQL</option>
                <option value=flask2>Flask with MySQL</option>
                <option value=django>Django</option>
                <option value=djangoorm>Django ORM</option>
                <option value=javafun>Java Fundamentals</option>
                <option value=javaoop>Java OOP</option>
                <option value=javaspring1>Java Spring 1</option>
                <option value=javaspringdata>Java Spring Data</option>
                <option value=javaspring2>Java Spring 2</option>
            </select>
        </div>
        <p><button type=submit class='btn btn-primary btn-md'>Ready!</button></p>    
    </form>
        
{% elif assignments|length %}

<a href="{% url 'dashboard:clear' %}" onclick="return confirm('Are you sure you want to delete these assignments? To confirm, click OK.');">
    <button type=submit class='btn btn-default btn-sm btn-block'>Clear List</button>
</a>

    <div class="list-group"><br>
    {% for assignment in assignments %}
        <a href="{% url 'dashboard:addtoplans' assignment.id %}" class="color{{assignment.base_points}} list-group-item list-group-item-action align-items-start">
            <div class="mb-1">
                <strong>{{assignment.title}}</strong> 
                <small>({{assignment.base_points}} pts)</small><br>
            <small class="mb-1">
                Est. Time: {{assignment.est_duration}} 
                ({{assignment.time_mult|floatformat}} mult.)
            </small>
            </div>
        </a>
    {% endfor %}
    </div>

{% endif %}
</div>

<div class="lane">
<h4 class=center><span class="glyphicon glyphicon-edit"></span> This Session</h4><hr>
{% if not commit|length %}
    <p><strong>Step 2: Plan Your Session</strong></p>
    
    <p>You'll earn points for each assignment completed in a session. There are  two ways you can multiply your points:</p>
    <p><strong>1. Time Multiplier</strong>: Multiplies each assignment's points if completed on time.</p>
    <p><strong>2. Session Multiplier</strong>: Multiplies your total points by the amount of assignments if you complete a time challenge.</p>
    <p><strong>Note:</strong> All assignments completed under 5 minutes will be logged as 5 minutes in our system following each session.</p>
    <br>
{% endif %}
{% if plans|length %}
    <div class="list-group">
    {% for assignment in plans %}
        <a href="{% url 'dashboard:remfromplans' assignment.id %}" class="color{{assignment.base_points}} list-group-item list-group-item-action align-items-start">
            <div class="mb-1">
                <strong>{{assignment.title}}</strong> 
                <small>({{assignment.base_points}} pts)</small><br>
            <small class="mb-1">
                Est. Time: {{assignment.est_duration}} 
                ({{assignment.time_mult|floatformat}} mult.)
            </small>
            </div>
        </a>
    {% endfor %}
    </div>
{% elif commit|length %}
    <div class="list-group">
    {% for assignment in commit %}
        <a href=# class="color{{assignment.base_points}} list-group-item list-group-item-action align-items-start">
            <div class="mb-1">
                <strong>{{assignment.title}}</strong> 
                <small>({{assignment.base_points}} pts)</small><br>
            <small class="mb-1">
                Est. Time: {{assignment.est_duration}} 
                ({{assignment.time_mult|floatformat}} mult.)
            </small>
            </div>
        </a>
    {% endfor %}
    </div>
{% endif %}<br>

</div>

<div class="lane">
<h4 class=center><span class="glyphicon glyphicon-pushpin"></span> Currently Working On</h4><hr>
{% if commit|length %}
    <p><strong>Step 3: Keep On Working</strong></p>
    
        <p>Good job! Now it's time to work!</p>
        <p>When you click the button, the timer for your first assignment will start. Each time you press the button, a new timer will start for a new assignment.</p>
    
    <p><a href="{% url 'dashboard:go' %}"><button type=submit class='btn btn-primary btn-md'>Go!</button></a></p><br>
{% endif %}
{% if plans|length or not commit|length %}
    <p><strong>Step 3: Keep On Working</strong></p>
    
        <p>After planning out your session, click the button to commit to working throughout this session.</p>
    
{% endif %}

    <p><a href="{% url 'dashboard:commit' %}">
{% if commit|length %} 
{% elif not plans|length %}
        <button type=submit class='btn btn-default btn-md disabled'>Set!</button>
{% elif plans|length %}
        <button type=submit class='btn btn-primary btn-md'>Set!&nbsp;<span class="badge">{{plans|length}}</span></button>
{% endif %}
    </a></p>


</div>
<div class="lane">
<h4 class=center><span class="glyphicon glyphicon-check"></span>  Done!</h4><hr>

    <div class="list-group score">
    <a class="list-group-item align-items-start score">
            <div class="d-flex w-100 justify-content-between">
            <p class="mb-1 score"><strong>Session Summary:</strong></p>
            </div>
            <p class="mb-1 score">
                {% if plans|length %}
                Number of Assignments: <big><strong>{{plans|length}}</strong></big><br>
                {% else %}
                Number of Assignments: <big><strong>{{commit|length}}</strong></big><br>
                {% endif %}
                Est. Time: <big><strong>{{duration}} +{{bonus}}</strong></big><br>
                Time Challenge: <big><strong>{{challenge}}</strong></big><br>
                Potential Score: <big><strong>{{potential}}</strong></big>
            </p>
        </a>
    </div>

</div>
</div>

{% endblock %}

apps/dashboard/templates/dashboard/dash2.html
{% extends "landing/base.html" %}

{% block content %}

<div class=kanban>

<div class="lane">
<h4 class=center><span class="glyphicon glyphicon-th-list"></span> Your Assignments</h4><hr>

{% if not assignments|length %}

    <p><strong>Step 1: Select a Track</strong></p>
    <p>Select a track from the menu:</p>

    <form method=POST action="{% url 'dashboard:assignments' %}">
        <div class=form_group>{% csrf_token %}
            <select name=track class=form-control>
                <option value=pyfun1>Python Fundamentals 1</option>
                <option value=pyfun2>Python Fundamentals 2</option>
                <option value=pyoop>Python OOP</option>
                <option value=flask1>Flask Fundamentals</option>
                <option value=mysql>MySQL</option>
                <option value=flask2>Flask with MySQL</option>
                <option value=django>Django</option>
                <option value=djangoorm>Django ORM</option>
                <option value=javafun>Java Fundamentals</option>
                <option value=javaoop>Java OOP</option>
                <option value=javaspring1>Java Spring 1</option>
                <option value=javaspringdata>Java Spring Data</option>
                <option value=javaspring2>Java Spring 2</option>
            </select>
        </div>
        <p><button type=submit class='btn btn-primary btm-md'>Ready!</button></p>    
    </form>
        
{% elif assignments|length %}

<a href="{% url 'dashboard:clear' %}" onclick="return confirm('Are you sure you want to clear this list?');">
    <button type=submit class='btn btn-default btn-sm btn-block'>Clear List</button>
</a>
 
    <div class="list-group">
    {% for assignment in assignments %}
        <a href=# class="color{{assignment.base_points}} list-group-item list-group-item-action align-items-start">
            <div class="mb-1">
                <strong>{{assignment.title}}</strong> 
                <small>({{assignment.base_points}} pts)</small><br>
            <small class="mb-1">
                Est. Time: {{assignment.est_duration}} 
                ({{assignment.time_mult|floatformat}} mult.)
            </small>
            </div>
        </a>
    {% endfor %}
    </div>

{% endif %}

</div>

<div class="lane">
<h4 class=center><span class="glyphicon glyphicon-edit"></span> This Session</h4><hr>

{% if not commit|length and current|length %}
    <p><strong>Last One Left!</strong></p>
        <p>You're in the final stretch! After completing this assignment, you'll be able to see your scores for this session. Keep going!</p>
{% elif not current|length %}

{% if session.on_time and done|length > 4 %}
<p><strong>Woah! What a session!</strong></p>
    <p>You clearly grapsed the material and worked hard get all your assignments done under the time estimate. Way to go! Work like you did this session every time and you'll be well on your way to becoming a self-sufficient developer.
        To start a new session, click this button.</p>
    <p><a href="{% url 'dashboard:archive' %}">
        <button type=submit class='btn btn-primary btm-md'>Do More</button>
    </a></p>
{% else %}
<p><strong>You did it!</strong></p>
    <p>Great session! You got all your work done and learned a lot at the same time.
        To start a new session, click this button.</p>
    <p><a href="{% url 'dashboard:archive' %}">
        <button type=submit class='btn btn-primary btm-md'>Do More</button>
    </a></p>
{% endif %}

{% endif %}

    <div class="list-group">
    {% for assignment in commit %}
        <a href=# class="color{{assignment.base_points}} list-group-item list-group-item-action align-items-start">
            <div class="mb-1">
                <strong>{{assignment.title}}</strong> 
                <small>({{assignment.base_points}} pts)</small><br>
            <small class="mb-1">
                Est. Time: {{assignment.est_duration}} 
                ({{assignment.time_mult|floatformat}} mult.)
            </small>
            </div>
        </a>
    {% endfor %}
    </div>

</div>

<div class="lane">
<h4 class=center><span class="glyphicon glyphicon-pushpin"></span> Currently Working On</h4><hr>

{% if current|length %}

    <p><a href="{% url 'dashboard:go' %}">
        <button type=submit class='btn btn-primary btm-sm btn-block'>Dozo!</button>
    </a></p>

    <div class="list-group">
    {% for assignment in current %}
        <a href=# class="color{{assignment.base_points}} list-group-item list-group-item-action align-items-start">
            <div class="mb-1">
                <strong>{{assignment.title}}</strong> 
                <small>({{assignment.base_points}} pts)</small><br>
            <small class="mb-1">
                Est. Time: {{assignment.est_duration}} 
                ({{assignment.time_mult|floatformat}} mult.)<br>
                Started: {{assignment.start_time|time:"P"}}
                ({{assignment.start_time|timesince}} ago)<br>
            </small>
            </div>
        </a>
    </div>

    <strong><p>Users working on this assignment:</p></strong>
    <ul>
    {% for current in all_current %}
    {% if current.pageid == assignment.pageid %}
    {% if current.user == request.user %}
    <li>{{current.user.username}} (you!)</li>
    {% else %}
    <li>{{current.user.username}} ({{current.user.first_name}})</li>
    {% endif %}
    {% endif %}
    {% endfor %}
    {% endfor %}
    </ul>
    
{% else %}

    <div class="list-group">
    <a class="list-group-item score">
        <p><strong>Assignment Summary:</strong></p>
    </a>
    </div>

    <div class="list-group">
    {% for assignment in stats %}
    <a href=# class="color{{assignment.base_points}} list-group-item list-group-item-action align-items-start">
            <div class="mb-1">
                <strong>{{assignment.title}}</strong> 
                <small>({{assignment.base_points}} pts)</small><br>
            <small class="mb-1">
                {{assignment.start_time|date:"P"}} - {{assignment.end_time|date:"P"}} ({{assignment.start_time|timesince:assignment.end_time}})<br>
                Score: {{assignment.actual|floatformat}} 
                out of {{assignment.potential|floatformat}} 
                {% if assignment.on_time %}(on time){% endif %}
            </small>
            </div>
        </a>
    {% endfor %}
    </div>

{% endif %}
</div>
<div class="lane">
<h4 class=center><span class="glyphicon glyphicon-check"></span>  Done!</h4><hr>

    <div class="list-group score">
    <a class="list-group-item align-items-start score">
            <div class="d-flex w-100 justify-content-between">
            <p class="mb-1 score"><strong>Session Summary:</strong></p>
            </div>
            <small class="mb-1 score">
                {% if current|length %}
                <p>Assignments remaining: <big><strong>{{remaining}}</strong></big></p>
                {% endif %}
                <p>Started: <big><strong>{{session.start|time:"P"}}</strong></big></p>
                <p>Finished: <big><strong>
                    {% if current|length %}
                    Not yet
                    {% else %}
                    {{session.end|time:"P"}}
                    {% endif %}
                </strong></big></p>
                {% if not current|length %}
                    <p>Duration: <big><strong>{{session.start|timesince:session.end}}{% if session.on_time %}
                     (on time){% endif %}</big></strong></p>
                {% endif %}
                <p>Score: <big><strong>
                    {{session.actual|floatformat}}</strong></big>
                    out of <big><strong>{{session.potential|floatformat}}</strong></big></p>
            </small>
        </a>
    </div>

{% if current|length %}
    <div class="list-group">
    {% for assignment in done %}
        <a href=# class="color{{assignment.base_points}} list-group-item list-group-item-action align-items-start">
            <div class="mb-1">
                <strong>{{assignment.title}}</strong> 
                <small>({{assignment.base_points}} pts)</small><br>
            <small class="mb-1">
                Est. Time: {{assignment.est_duration}} 
                ({{assignment.time_mult|floatformat}} mult.)<br>
                {{assignment.start_time|time:"P"}} - {{assignment.end_time|time:"P"}} 
                ({{assignment.start_time|timesince:assignment.end_time}})
            </small>
            </div>
        </a>
    {% endfor %}
    </div>
{% endif %}
</div>

</div>


{% endblock %}

apps/dashboard/templates/dashboard/newsfeed_temp.html
<!-- Display online users if not alone -->
{% if online_users|length > 1 %}
<h6>Other Members Online:</h6>
<p>
    {% for user in online_users %}
        {% if not user == request.user %}
            {{user.username}} ({{user.first_name}})<br>
        {% endif %}
    {% endfor %}
</p>
{% endif %}




{% for user in online_users %}
{% if online_users|length == 1 %}
    {{user.username}} (just you!)
{% else %}
    {{user.username}} ({{user.first_name}}) &nbsp;
{% endif %}
{% endfor %}



<div>
        <h6>
        Welcome, <strong>{{request.user.first_name}}</strong>! Let's crush those assignments!<br>
        <small>
            You logged in on <strong>{{request.user.last_login}}</strong><br>
    </h6>
</div>